name: Build iOS App
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    # Самый новый сервер, где ЕСТЬ Xcode 16
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode 16.0
      run: sudo xcode-select -s /Applications/Xcode_16.0.app

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install MAUI Workload
      run: dotnet workload install maui-ios

    - name: Publish iOS App (Unsigned)
      # Мы убрали все лишние флаги, оставили только базу
      run: dotnet publish -f net8.0-ios -c Release -p:ArchiveOnBuild=true -p:RuntimeIdentifier=ios-arm64 -p:EnableCodeSigning=false -p:CodesignKey="" -p:CodesignProvision=""
    
    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: HexStressApp
        path: bin/Release/net8.0-ios/ios-arm64/publish/*.ipa