name: Build iOS App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Install MAUI Workload
      run: dotnet workload install maui-ios

    - name: Publish iOS App (Unsigned)
      # Добавлен флаг -p:_SuppressSdkVersionCheck=true чтобы игнорировать ошибку Xcode
      run: dotnet publish -f net9.0-ios -c Release -p:ArchiveOnBuild=true -p:RuntimeIdentifier=ios-arm64 -p:CodesignKey="" -p:CodesignProvision="" -p:_SuppressSdkVersionCheck=true

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: HexStressApp
        path: bin/Release/net9.0-ios/ios-arm64/publish/*.ipa