name: Build iOS App
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install MAUI Workload
      run: dotnet workload install maui-ios
    - name: Publish iOS App (Unsigned)
      # Добавлен флаг EnableCodeSigning=false для полного отключения подписи
      run: dotnet publish -f net8.0-ios -c Release -p:ArchiveOnBuild=true -p:RuntimeIdentifier=ios-arm64 -p:EnableCodeSigning=false -p:CodesignKey="" -p:CodesignProvision=""
    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: HexStressApp
        path: bin/Release/net8.0-ios/ios-arm64/publish/*.ipa